services:
  - type: web
    name: profanity-replacement-app
    env: python
    buildCommand: |
      chmod +x build.sh
      ./build.sh
      python -m pip install --upgrade pip
      pip install --no-cache-dir -r requirements.txt
    startCommand: gunicorn -c gunicorn.conf.py run:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONHASHSEED
        value: "0"
      - key: PYTHONDONTWRITEBYTECODE
        value: "1"
      - key: OMP_NUM_THREADS
        value: "1"
      - key: MKL_NUM_THREADS
        value: "1"
      - key: NUMEXPR_NUM_THREADS
        value: "1"
